t.formats/mangling/mangling
Demangler testsuite for test demangling of variable.
=> demangler variable testsuite

t.anal/java/java, t.asm/lh5801/lh5801, t/cmd_ib
The corresponding commits in radare/radare2 aren't yet submitted, but will soon be.
=> Tests for LH5801. Also a minor fix for Java.

t/cmd_search
Tests normal x86 search, x86 with regexp, and branch delay slot support (mips).
=> New test for rop search

t.formats/pe/normal, t/cmd_ib, t/cmd_info
This is for fix https://github.com/radare/radare2/pull/2376
=> Fix cmd_info, cmd_ib and t.formats/pe/normal

t.anal/java/java, t/cmd_ib, t/cmd_info
This test is to fix this https://github.com/radare/radare2/pull/2379
=> Updated info test

t.asm/msp430/msp430
https://github.com/radare/radare2/issues/2547#issuecomment-100647145
=> Issue 2547 - Add test cases for MSP430

t/search/hex
i think this test catches the problem of radare/radare2#2541
=> + added "binmask seek search (mips)" test in search/hex (broken=1)

t.asm/x86/nz/x86
I only wrote a few, to check for edge cases. Is that enough?
=> Add tests for x86.nz jumps

t.formats/omf/omf
Omf tests fix for the last pull request on radare2 (https://github.com/radare/radare2/pull/2625)
=> fix omf tests

t/cmd_pf
=> pf: Add register test

t.tools/rabin2/rabin2
Please carefully review the tests to check that the tests I've added are what we expect.
=> t.tools/rabin2: extend vaddr/paddr/baddr/laddr tests

t.formats/elf/pie
derp
see comments in 8d3300d3108848ec8df41b2d17036de272a8b1ff
=> Fix offset of pie asm.midflags test to match binary

t.esil/6502
includes tests for:
LDA,LDX,LDY in all its addressing modes
STA,STX,STY in all its addressing modes
LSR,ASL in all its addressing modes
INY,DEY,INX,DEX
flags
This is still WIP. mnay more opcodes need tests
and its implementation as well
=> 6502 esil regression tests

t/seek/redodups
First must be merged this https://github.com/radare/radare2/pull/3618
=> added seek dup test see #3474 r2

t/search/avr
Change tests for search commands in AVR file
=> Add new test and correct older

t/search/bug_3788
test case for this PR: https://github.com/radare/radare2/pull/3813
=> adds cmd.hit test for bug 3788

t/cmd_zF
related to https://github.com/radare/radare2/issues/3816
=> test for flirt

t.formats/pe/export_names
Some PE export tests added (https://github.com/radare/radare2/pull/3875)
=> 3875 test added

t.esil/arm-16
=> Added new tests for cpsr in ARM ESIL

t/cmd_pd
pull request to add test for issue #3084
=> added test for issue #3084: pd 0 should print 0 instructions

t.esil/arm-16, t.esil/arm-64
I already started to work in order to un-break the BROKEN ones.
=> ARM ESIL: added some tests, some of them broken

t.tools/rahash2/rahash2
also, corrected zero length md5 test
#150
=> added tests for rahash2 -c parameter

t/cmd_rop
test case for https://github.com/radare/radare2/issues/4319
=> add rop search case of matching multiple instr

t/cmd_pd
If there's a better place to put this test, let me know. And note that it doesn't pass without radare/radare2#4323.
=> Test case for radare/radare2#4323

t/cmd_types
I noticed that the code worked fine but the tests were wrong so I fixed the broken tests and everything shall be well and good
=> fixing broken 2 tests in types

t/cmd_types
=> fixing tests for after fixing `t instruction` 

t/cmd_types
https://github.com/radare/radare2/pull/4399
=> adding more tests for the t

t.asm/ebc/ebc
Changes introduced in https://github.com/radare/radare2/pull/4443
=> Add test for indirect and external EBC call32

t.asm/ebc/ebc
Related to PR https://github.com/radare/radare2/pull/4446
=> Add test for not EBC instruction

Makefile, t.anal/m68k/m68k
See https://github.com/radare/radare2/pull/4505
=> regression test for commit d637a74a

Makefile, t.anal/m68k/m68k, t.anal/m68k/visual, t.asm/m68k/m68k
Tests for https://github.com/radare/radare2/pull/4515
=> m68k tests

t.tools/rahash2/rahash2
Correct the test case for blowfish algorithm.
=> correct blowfish test

t.asm/mips/mips, t.asm/mips/mips.gnu
https://github.com/radare/radare2/pull/4600
=> mips: use a negative offet when testing addui

t.tools/rahash2/rahash2, t/cmd_wop
update test for `rahash2 -D` and `woD`
=> update tests for woD and rahash -D option

t.tools/rahash2/rahash2
=> update rc2 test

t.tools/rahash2/rahash2
I have fixed test case for rol and ror too. I think now it should not break.
=> add test for cbc and ecb

t/cmp/bitmask
test related to the https://github.com/radare/radare2/pull/4662
=> added test for the new cx bitmask feature

t.esil/math
Signed-off-by: Damien Zammit <damien@zamaudio.com>
=> Add float math tests

t.archos/Linux-x86_64/dbg_oo
Signed-off-by: Damien Zammit <damien@zamaudio.com>
=> dbg_oo: Fix path of ls

t.formats/elf/helloworld-gcc-elf, t/cmd_pd_bugs, t/cmd_wop, t/hash, t/manyundo, t/metadata
Unfortunately there are more broken tests...
I added BROKEN when the fix was not clear/easy stuff but it would instead require some better thinking about the problem
=> t: other fixes

t.esil/esil
+ added one un-broken and two broken tests in t.esil/esil
=> ESIL memory write issues with endianness, both MIPS and non-MIPS

t.esil/esil
ESIL: un-broken big endian memory write (on big endian arch)
=> ESIL: un-broken big endian memory write

t/cmd_pf_elf
New tests for the structures in the elf struct formats
=> Added test for elf32 and elf64 structures

t.asm/x86/nz/x86
Remove the "br" from tests that are fixed
=> remove br from working tests

t/cmd_pd
=> Added #5228 test.

t/cmd_seek
Add a test for seeking backwards.
=> add seek backwards test

t.anal/others_anal/arj
for issue https://github.com/radare/radare2/issues/5537
=> Added test for `arj` with flags too

t.asm/msp430/msp430
=> Add a test for a missing msp430 #1 constant register

t.archos/Linux-x86_64/dbg_bps
See https://github.com/radare/radare2/pull/5583 for more information.
=> Improve breakpoint tests to handle the fix in #5583

t.archos/Linux-x86_64/dbg_step
=> dbg_step "ds on jmp reg" should be fixed now

t.archos/Linux-x86_64/dbg_step
adds additional dbg testcases and fixes one intermitent pass/fail
=> dso problem

Makefile, run_unit.sh, unit/test_debruijn.c
test_debruijn: fix use of r_debruijn_offset
=> unit: exit with error if unittests fail

unit/test_str.c
together with https://github.com/radare/radare2/pull/5915/files
=> unit: remove brokeness from some tests on r_str

t.formats/dex/classes
R2 PR: https://github.com/radare/radare2/pull/5957
=> fix Dalvik flags test

t.anal/x86/emu
- ported to new format and types
=> Fix emu tests for function signatures

t/cmd_hash
Tests for https://github.com/radare/radare2/pull/6132
=> Add cmd_hash tests (#! #? and comments)

t.asm/arm/thumb
To accompany radare/radare2#6189
=> Fix tests for arm thumb

t.anal/arm/arm_32, t.anal/arm/arm_cs, t.esil/arm-16
This documents a possible bug reported in [issue #6387](https://github.com/radare/radare2/issues/6387).
=> [t.esil] arm-16: add test for LDR (register) (#6387)

t.esil/arm-32
Don't worry. I have a pull request coming soon that fixes all these tests. I've been writing them as I've been working.
=> Many new STR tests.

t.esil/arm-32
A couple more STR tests before the pull request.
=> Added negative index store tests

t/cmd_flags
This will catch https://github.com/radare/radare2/pull/6439
=> Improve `fl` test

t.anal/others_anal/stackptr
To be merged after https://github.com/radare/radare2/pull/6620 since i didn't marked it BROKEN
=> Add test for recursive stackptr calculation

t.anal/others_anal/meta
This creates a temporary project for testing. How should I go about removing the project after the test?
=> Test for #6834

t.archos/Linux-x86_64/dbg_step
Test for https://github.com/radare/radare2/pull/6736
=> Dcu regression

t.esil/arm-16, t.esil/arm-32
Adds arm-32 and thumb tests for the changes in PR radare2/#6893 (issue r2/#6884)
=> ARM arithmetic emulation tests for radare2/#6884

t.anal/others_anal/xref
Modified tests for code that gets PC from stack
=> Test for #6902

t.asm/arm/thumb
Added test for: https://github.com/radare/radare2/pull/6968
=> Added test for thumb BL

t.asm/arm/thumb
Test for https://github.com/radare/radare2/pull/6994
=> Test for pop rsequence

t.anal/arm/arm_16
Regression test for radare/radare2#6979
=> Added test for pull request #6979 to print filtered strings containing newlines

t.esil/cmd_aea, t/cmd_json
Basic tests for aea family of commands.
=> aea tests #7035

t/cmd_pd
Last test looking a bit silly right now.
=> Tests for radare/radare2#7212

t/metadata
The additional test should not segfault.
=> Tests for #7221

t/grepcol3
https://github.com/radare/radare2/pull/7284
=> Add grepcol3 test for PR 7284

t/cmd_ahi
=> Added test for issue radare/radare2#7315

t.esil/arm-64
to be merged after: https://github.com/radare/radare2/pull/7371
=> Add test for arm64 movz and movk ESIL

t/cmd_pd
Tests for radare/radare2#7375.
=> Add tests for mov flag cmt

t/cmd_pd
Fixed test for radare/radare2#7379.
=> Fix push cmt test

t/cmd_pd, t/display_flag
=> Test for fcn name cmt alignment

t/cmd_pd
Tests for radare/radare2#7386.
=> Tests whether flag cmt is put first and shown only once

t.anal/others_anal/reflines, t.anal/others_anal/vars, t/comments, t/noreturn
Fixed tests for radare/radare2#7424.
=> Fixed tests that have callee info cmts

t.anal/x86/emu, t/comments
Fixed tests for radare/radare2#7452.
=> Fixed some comment spacing in tests

t/cmd_project
Test for https://github.com/radare/radare2/pull/7485
=> Add test for prj.name saved in project

t/cmd_print
this PR is related to https://github.com/radare/radare2/pull/7508
=> Add tests for pib command

t/cmd_print
related to radare/radare2#7509
=> Add pI check when requested size > blocksize

t.formats/elf/dynimports, t.formats/elf/elf-relro, t.formats/elf/elf_malformed, t.formats/elf/symbols, t/cmd_i
update tests to cope with ELF WEAK symbols
=> update ELF tests to cope with WEAK symbols

t.tools/r2/seek_undo_redo
A test for the problem described in [issue 7527](https://github.com/radare/radare2/issues/7527).
=> radare2 repo issue #7527

t/cmd_pd
=> Test for asm.cmtoff

t/cmd_pd
=> Tests whether asm.leahints cmts are normal cmts

unit/.gitignore, unit/test_skiplist.c
tests for https://github.com/radare/radare2/pull/7657
=> add unit test for skiplist https://github.com/radare/radare2/pull/7657

t.archos/Linux-x86_64/dbg_bps
related to https://github.com/radare/radare2/issues/7655
=> add tests for dbd and dbe commands

t.extras/dwarf/dwarf
Test update for https://github.com/radare/radare2-extras/pull/121
=> update dwarf test - iddd array and json

t/feat_grep
For https://github.com/radare/radare2/pull/7672 pull request.
=> intgrep tests

t/cmd_pd
=> Tests use of r_str_escape for anal strings

t/cmd_pd
Fixed tests for radare/radare2#7760.
=> Test whether 'u' prefix is added to wide UTF-16 strings

t/disasm_describe
=> Add tests for PR #7772

t.esil/apple, t/cmd_pd
=> Tests use of r_str_escape for ASCII anal addr strings

t/cmd_pd
Tests for radare/radare2#7990.
=> Tests for asm.asciidot

t/cmd_pd
=> Test asm.strenc guess of whether string is utf8

t/cmd_pd
=> Tests whether guess for utf16le string has been tightened up

t/cmd_project
59c5a49623476df550560ec510bdff1b4c82dbba fixes this issue
=> Removed broken flag in projects

t/cmd_i
Tests for radare/radare2#8237.
=> Tests whether iz/izz shows Unicode blocks correctly

t/cmd_write
=> Tests whether r_str_unescape correctly handles octal escapes

t.anal/arm/vars
Output changes b/c of `shdr -> phdr`
=> Fix t.anal/arm/vars

t/cmd_ahi
After https://github.com/radare/radare2/pull/8396 is applied
=> Fix immbase, ahi 2 => ahi b => binary, ahi 1 => ahi 1 => string

unit/test_addr_interval.c
Test for https://github.com/radare/radare2/pull/8475
=> Add test for r_addr_interval.h

t/metadata
Tests for radare/radare2#8464.
=> Tests whether C[Chsdmf][*] works properly

t/metadata
Fixed test for radare/radare2#8525.
=> Tests whether hidden metadata is shown as "hidden"

t/metadata
Tests for radare/radare2#8532. More tests for radare/radare2#8464.
=> Tests for C[hsdmf]j

t/metadata
=> Tests whether Cs differentiates between ascii and non-ascii strings

t/metadata
Tests for radare/radare2#8570.
=> Tests whether Csj shows enc and ascii properties correctly

t/metadata
Fixed tests affected by radare/radare2#8577.
=> Fix tests affected by Csj encoding strings as base64

t/metadata
Add and fix tests affected by radare/radare2#8605.
=> Tests whether Cs shows unfiltered ascii and latin1 strings correctly

t/cmd_i, t/cmd_pd, t/metadata
Reverts radare/radare2-regressions#1033
=> Revert "Fix tests affected by string_scan_range escaping backslashes"

t/cmd_i
Need https://github.com/radare/radare2/pull/8645 to be merged.
=> Add IA64 binary test

t.archos/Linux-x86_64/dbg_fds, t/cmd_open, t/cmd_pd, t/cmd_visual
This PR attempts to add regression tests for the r2 crashes reported in the following PRs:
- https://github.com/radare/radare2/issues/8503
- https://github.com/radare/radare2/issues/8502
- https://github.com/radare/radare2/issues/8500
=> Regression tests for fixed r2 crashes

t/metadata
Modified test for radare/radare2#8652.
=> Tests whether Csg works correctly

t/metadata
Tests for radare/radare2#8669.
=> Tests whether Cs. shows string at current address

t/cmd_pd
=> Tests whether string at src is shown if dst is stack for x86_cs MOV

t/metadata
Tests for radare/radare2#8689.
=> Tests whether Cs.. works properly

t/metadata
Tests for radare/radare2#8700.
=> Tests whether Csg/Csa <size> works properly

t/metadata
Tests for radare/radare2#8702.
=> Tests whether there are multiple Cs entries after Csg/Csa <size>

t/metadata
Tests for radare/radare2#8724.
=> Tests whether Cs* output is correct for Csa strings

t/metadata
Tests for radare/radare2#8783.
=> Tests whether Cd- <size> <repeat> works correctly

t/cmd_graph
Tests for radare/radare2#8841 that tries to fix radare/radare2#8788.
=> Tests whether radare/radare2#8788 is fixed

t/metadata
Tests for radare/radare2#8847.
=> Tests whether Cs8 works correctly

t/metadata
Tests for radare/radare2#8855.
=> Tests whether cfg.escbslash works properly for Cs

unit/test_unum.c
I added tests for following for R_APIs
* r_num_minmax_swap
* r_num_minmax_swap_i
* r_num_units
* r_between
=> Add test for unum

t/feat_arroba
For https://github.com/radare/radare2/pull/8868
=> Add Arroba/@ tests

t/cmd_i, t/cmd_pd, t/metadata
Tests for radare/radare2#8882. Cherry-picked some commits.
=>  Tests whether str.escbslash works correctly with iz

t.anal/others_anal/stref, t.esil/arm-64
Tests for radare/radare2#8971.
=> Tests whether likeliness of arm64 cbz and cbnz is correct

t.esil/arm-16
Tests for radare/radare2#8983.
=> Tests whether likeliness of arm16 cbz and cbnz is correct

unit/test_hex.c
Related to PR https://github.com/radare/radare2/pull/8984
Add some test case for r_hex_from_c.
=> Add unit/test_hex.c

unit/test_unum.c
Add some tests for https://github.com/radare/radare2/pull/8942.
All of them are passed in my local environment
.
=> Add tests for unit/test_unum.c

t/cmd_p-
Related fix: https://github.com/radare/radare2/pull/8990
=> Add test for p-h out of bounds access

t/cmd_pd
for https://github.com/radare/radare2/pull/9002
=> Tests for pdJ

t/cmd_pd
for https://github.com/radare/radare2/pull/9004
=> pdJ string test

t.tools/rax2/rax2
Fix for changes of https://github.com/radare/radare2/pull/9007#issuecomment-351157454
=> Fix tests for removing rax2 -P

t/cmd_pd
for https://github.com/radare/radare2/pull/9037
=> Add pdJ midflags reloc test

unit/test_hex.c
Test for https://github.com/kriw/radare2/commit/22f18e848d27aee880d198c8965434430b301cfd
=> add test_r_hex_no_code

t/cmd_pd
For https://github.com/radare/radare2/pull/9066
=> Tests for string in opcode in pdj and pdJ

t.esil/x86-32
Additional test for esil (see https://github.com/radare/radare2/pull/9074)
=> Add div cl x86-32 test in t.esi/x86-32

t.formats/others/hexfile
for https://github.com/radare/radare2/pull/9106
=> Adapt hexfile test to PIC plugin name change

t/cmd_pd
=> Tests whether disasm honors bin.strpurge

r2r
=> r2r -a: fix handling of multiline cmds from stdin

t/cmd_pd
Tests for radare/radare2#9194.
=> Tests fine-grained purging of strings using bin.strpurge (disasm only)

t/cmd_pd
Tests for radare/radare2#9210.
=> Tests bin.strpurge with iz

t/cmd_pd
Tests for radare/radare2#9223.
=> Tests bin.strpurge's support for preventing string purge (single addr)

t/cmd_pd
Tests for radare/radare2#9225.
=> Tests bin.strpurge's support for preventing string purge (addr range)

t/cmd_i_temp
Tests for radare/radare2#9245. Tests will be moved to `new` once they are complete and if they have been merged in.
=> Tests whether iz- (current seek) works

t/cmd_i_temp
=> Tests whether iz- accepts addr as arg

t.anal/arm/arm_16
This test will pass after https://github.com/radare/radare2/pull/9271 is merged
=> Test arm be 16

t.formats/smd/smd
See 49bc9ef024fc , b188f40e42 on radare2 repo for the bugs
=> Add test for SMD maps and entrypoint

new/db/cmd/cmd_pd
=> Tests whether invoking pd twice with asm.emu.pre works

bins/rr2/input_redirection.rr2, t.archos/Linux-x86_64/feat_input_redirect
Tests for https://github.com/radare/radare2/pull/9383
=> Fix input redirection tests

new/db/cmd/cmd_pd
=> Tests for duplicate string comment when using asm.emu.str with absolute addressing

t.esil/brainfuck
Fixed test for radare/radare2#9495.
=> Tests whether bf unbalanced loop crashes with no aes

new/db/cmd/cmd_i
Radare2 bug is on https://github.com/radare/radare2/issues/9370
=> Add regression testing for radare2 #9370

new/bin/r2r.js, new/common.js, new/db/cmd/feat_input, new/index.js
Highlights trailing whitespace as below:
=> Highlight trailing whitespace in diff

t/cmd_project
See https://github.com/radare/radare2/issues/9500
BROKEN=1 right now. Previous tests for Pd are preserved and not marked as broken of course.
=> Test Pd deletes project dir too, not only rc file

new/db/cmd/cmd_i
Tests for radare/radare2#9561.
=> Tests whether izz/izzj works with -n without using rabin2

new/bin/r2r.js
=> Make `r2r.js -e` print it's not implemented

t.esil/x86-32
=> Tests whether x86 esi pic thunk inlining works correctly

t.anal/x86/cmd_a8
=> Add test for a8

t.esil/x86-32
Added to test for radare/radare2#9759.
=> Add to inline x86 pic thunk test

new/index.js
So that DOS crlf line endings don't mess up testing on Windows.
=> Mass replace \r\n with \n

new/db/asm/arm_16
many new tests for radare thumb-2 implementation (both disassembler and assembler)
=> Arm thumb/opcodes up to s

t.esil/arm-16
Related to https://github.com/radare/radare2/pull/9795
=> Fix arm thumb2 IT instruction “fail” address

new/db/cmd/cmd_pd
=> Tests whether asm.emu.strinvert works properly

new/db/cmd/cmd_pd
=> Tests whether asm.emu.strflag works properly

new/db/cmd/cmd_pf2
=> Tests whether pf *z works with 64-bit addr

new/db/cmd/cmd_i
Fixed test for radare/radare2#9872.
=> Tests whether iee's paddrs are fixed

new/db/cmd/feat_variables
=> Tests whether $$$ works properly

new/db/cmd/feat_variables
Test for radare/radare2#10007.
=> Tests whether seek does not change on pdf @ addr

new/db/cmd/feat_variables
Test for radare/radare2#10010.
=> Tests whether $$$ in nested cmd works properly

new/db/cmd/cmd_pd
Tests for radare/radare2#10059.
=> Tests whether pdJ escaping works properly

new/db/cmd/cmd_pd
Test for radare/radare2#10071.
=> Tests whether arm asm.varsub supports asm.pseudo for fp

new/db/cmd/cmd_pd
Test for radare/radare2#10074.
=> Tests whether arm asm.pseudo supports asm.varsub_only for fp

new/db/cmd/cmd_ps
Test for radare/radare2#10089.
=> Tests whether psx escapes newlines

t.anal/others_anal/xref
Related to https://github.com/radare/radare2/issues/10066
=> Basic regressions to compare results from aar and afr

new/db/cmd/cmd_pd
Test for radare/radare2#10178.
=> Tests whether arm asm.var.sub (fp) works properly with asm.ucase

new/db/cmd/cmd_pd
This fixes tests for this pr https://github.com/radare/radare2/pull/10184
=> Fixed comments aligned to default column 71 (honor asm.cmt.col)

new/db/cmd/cmd_i
Added tests for radare/radare2#10317.
=> iSq and iSSq tests

new/db/tools/rabin2, new/index.js
Added test for radare/radare2#10358.
=> rabin2 -g test

new/db/cmd/cmd_pd
Added tests for radare/radare2#10516.
=> asm.imm.str=true and asm.cmt.right=false tests

new/db/cmd/cmd_pd
Test for radare/radare2#10551.
=> asm.imm.str test: false positive if string shortened

new/db/cmd/cmd_pd
Added test for radare/radare2#10556.
=> Tests whether asm.imm.str string is hidden due to flag

new/bin/r2r.js, new/common.js, new/db/tools/rabin2, new/index.js, t.tools/rabin2/rabin2, tests.sh
=> Add support for single-line EXPECT_ERR in new r2r

new/db/tools/rabin2
Test for radare/radare2#10742.
=> Tests whether rabin2's json output ends with newline

new/db/tools/rabin2
Deleted/modified tests for radare/radare2#10789.
=> Show that missing last newline can be handled by new r2r

new/db/tools/rax2
Added test for radare/radare2#10840.
=> Add rax2 test for negative hex numbers with 'f' at end

unit/.gitignore, unit/minunit.h, unit/test_vector.c
for https://github.com/radare/radare2/pull/10859
=> RVector and RPVector unit tests

unit/test_vector.c
@ret2libc reopened from this repo
https://github.com/radare/radare2/pull/10882 should be merged before this.
=> Adapt unit tests for vector refactoring

new/db/formats/smd
Changed test for radare/radare2#10995.
=> Test whether smd baddr == 0

new/db/cmd/cmd_pd
Added test for radare/radare2#11005.
=> Test for #10989 double pre-disasm bug

new/db/asm/x86_32, new/db/asm/x86_64
Added tests for radare/radare2#11050.
=> Added tests for 32-bit & 64-bit lea <reg>, <constant>

new/db/cmd/cmd_i
Related to https://github.com/radare/radare2/pull/11083
=> Fix testcases for `izzj`

new/db/tools/rabin2
Added test for radare/radare2#11130.
=> Add iee hvaddr rva test

new/db/tools/rabin2
Fixed tests for radare/radare2#11210.
=> Fix paddr in rabin2 -ee tests

old/t.archos/Linux-x86_64/bug_6678, old/t.archos/Linux-x86_64/cmd_mem_reuse_num_struct, old/t.archos/Linux-x86_64/dbg_seginfo, old/t.archos/Linux-x86_64/feat_input_redirect, old/t.archos/Makefile
r2 PR: https://github.com/radare/radare2/pull/11262
=> Travis debug

new/db/cmd/cmd_af, new/db/tools/radiff2
Added test for radare/radare2#11339.
=> Test for missing bb fix

new/db/asm/x86_32, new/db/asm/x86_64
Added tests for radare/radare2#11375.
=> Tests whether x86.nz dest size for mov [reg], imm is reg size

new/db/asm/x86_32, new/db/asm/x86_64
https://github.com/radare/radare2/pull/11466
=> Added new tests for inc/dec

new/db/asm/x86_32
Those tests just seem wrong. capstone confirms.
=> db/asm/x86_32: fix some wrong tests

new/db/tools/rahash2
https://github.com/radare/radare2/pull/11508
=> new/db/tools/rahash2: Fix ror and rol tests

old/t/cmd_types
r2 PR: https://github.com/radare/radare2/pull/11782
=> cmd_types: fix test after implementing sorting

new/db/cmd/cmd_pd2
Added test for radare/radare2#11854.
=> Add test for VV esil function comment no-newline fix

new/db/formats/elf/elf-riscv64
Fixed test for radare/radare2#11887.
=> Fix test due to setting of elf entry0 hvaddr from r2 ehdr segment

new/db/cmd/cmd_pd2
Add tests for radare/radare2#11973.
=> Add tests for asm.bb.middle

new/db/anal/x86_2
Added test for radare/radare2#12008.
=> Add test for r_anal_fcn_split_bb FITFCNSZ fix

new/db/anal/x86_2
Added tests for radare/radare2#12045.
=> Add x86_2 asm.bb.middle tests

new/db/cmd/cmd_pd2
Added test for radare/radare2#12050.
=> Add test that checks whether pdf sparse hides code

new/db/cmd/cmd_af, new/db/cmd/cmd_pd
Added test for radare/radare2#12058.
=> Add afb+ test

new/db/cmd/cmd_af
Added test for radare/radare2#12094.
=> Test afb+ with wrong size

new/db/anal/x86_2
Changed test for radare/radare2#12110.
=> Test whether af-* removes jmprefs

new/db/cmd/cmd_pd2
Added test for radare/radare2#12143.
=> Test whether r_core_print_disasm_json() honors asm.bb.middle and pdfj ignores asm.bb.middle

new/db/cmd/cmd_pdr
Added test for radare/radare2#12178.
=> Add pdrj test

new/db/cmd/cmd_pdr
Added test for radare/radare2#12193.
=> Test whether pdrj ignores asm.bb.middle

new/db/cmd/cmd_pd2
Added test for radare/radare2#12204.
=> Test whether r_core_disasm_pdi() honors asm.bb.middle

new/db/cmd/midbb
Added test for radare/radare2#12218.
=> Test whether r_core_print_disasm_instructions() honors asm.bb.middle

new/db/anal/x86_2
Fixed tests for radare/radare2#12317.
=> Test whether missing space is added in afi locals

new/db/anal/x86_2
Fixed tests for radare/radare2#12318.
=> Remove trailing spaces from afi output

new/db/formats/elf/core
Added test for radare/radare2#12325.
=> Test whether segment comments are shown if there are no sections (elf)

new/db/formats/elf/core
Fixed test for radare/radare2#12362.
=> Fix jump without refline due to comment

new/db/cmd/cmd_pd2
Added test for radare/radare2#12371.
=> Test whether ta hint works even if asm.cmt.right=false

new/db/anal/msp430, new/db/asm/msp430
goes with https://github.com/radare/radare2/pull/12447
=> small Msp430 improvements

new/db/cmd/cmd_seek
Added test for `so -N` for radare/radare2#12469.
=> Test so -N

new/db/cmd/cmd_seek
Added test for radare/radare2#12505.
=> Test whether pd -N start addr is equal to so -N

new/db/cmd/cmd_seek
Added test for radare/radare2#12509.
=> Test whether Vpk hang regression fix has been moved into prevop_addr()

new/db/cmd/cmd_seek
Modified test for radare/radare2#12545.
=> Test whether pd -N is fixed

new/db/cmd/cmd_pd2
Added tests for radare/radare2#12564.
=> Test asm.bbline when there are refs from and to addr

new/db/cmd/cmd_pd2
Modified test for radare/radare2#12568.
=> Test asm.bbline when there is backwards ref to and ref from addr

new/db/esil/x86-32
Added test for radare/radare2#12586.
=> Add test for 'bts dword [esp], eax' esil

new/db/anal/others
Tests for P: Fix wrong splitting of functions in aac https://github.com/radare/radare2/pull/12606
=> Check that functions are not splitted without overlapping blocks

new/db/cmd/cmd_i
Added tests for radare/radare2#12597.
=> Test whether spec-following r_str_escape_utf8_for_json() works properly

new/db/cmd/cmd_pd2
Added test for radare/radare2#12641.
=> Test esil function comment refline when there is jump to addr

new/db/cmd/cmd_ax
Added test for radare/radare2#12668.
=> Add test for axtj when nofunc and noflag

new/db/cmd/cmd_agf
Test for PR: https://github.com/radare/radare2/pull/12666
=> Add test that checks that reloc symbols are resolved in agfj

new/index.js
There's also the cmd/cmd_json tests.
=> Execute as json test, tests in json dir only

new/db/anal/others, new/db/cmd/cmd_agC, new/db/cmd/cmd_pd
PR: https://github.com/radare/radare2/pull/12786
=> Add test that checks that noreturn handling of reloc is correct and fix existing tests

new/db/cmd/feat_arroba
for https://github.com/radare/radare2/pull/12815
=> Expect int values for e scr.color

new/db/cmd/cmd_i
"Fixed" test for radare/radare2#12838.
=> "Fix" cmd_i test for radare/radare2#12838

new/db/json/json
merge this after this will be merged
https://github.com/radare/radare2/pull/12868
=> Add aflmj json command

new/db/tools/rafind2
Added tests for radare/radare2#12866.
=> Test whether rafind2 -S works for UTF8 chars > U+00ff

new/db/json/json
Merged here: https://github.com/radare/radare2/pull/12884
=> add pifj and pifcj

new/db/cmd/cmd_json
fix test for radare/radare2#12976
=> Fix test for radare2/12976

new/db/cmd/cmd_flags, new/db/formats/elf/helloworld-gcc-elf, unit/test_rbtree.c
r2 PR: https://github.com/radare/radare2/pull/12957
=> Flag spaces

unit/test_event.c, unit/test_spaces.c
merge https://github.com/radare/radare2-regressions/pull/1676 first
=> Add and update Unit Tests for REvent 

bins/headers/12272.h, new/db/cmd/12272.h, new/db/cmd/types
Added test for radare/radare2#13006.
=>  Test whether typedef'd (anonymous) structs are supported

bins/headers/hdr1.h, bins/headers/hdr2.h, new/db/cmd/types
Added test for radare/radare2#13014.
=> Test whether typedef to anonymous struct in more than 1 header is supported

new/db/cmd/types
Fixed tests due to radare/radare2#13015.
=> Fix tests due to t-* resetting tcc's anonymous symbol counter

new/db/tools/rax2
Create a test case for rax2
`rax2 -S "hello\x2Aworld ZYX\234abc\n"`
for pull request in radare[#12985](https://github.com/radare/radare2/pull/12985)
=> test case for rax2 -S

new/db/cmd/types
Added test for radare/radare2#13020.
=> Test whether double's type is F

new/db/anal/others_2
Added test for radare/radare2#13124.
=> Check whether aac names import trampolines

new/db/cmd/cmd_graph, new/db/cmd/cmd_pd
Fixed tests for radare/radare2#13180.
=> asm.strenc -> bin.strenc

unit/test_buf.c, unit/test_flags.c, unit/test_hex.c, unit/test_util.c
r2 PR: https://github.com/radare/radare2/pull/13267
=> Fix some leaks from unit tests

new/db/cmd/cmd_flags, new/db/formats/elf/helloworld-gcc-elf
r2 PR: https://github.com/radare/radare2/pull/13182
=> Adjust tests for symbols.objects/sections flag spaces

new/db/anal/x86_32, new/db/anal/x86_64, new/db/cmd/cmd_foreach, new/db/cmd/cmd_pdr
Unbroke and fixed tests for radare/radare2#13193.
=> Unbreak get function in, node before entry test

new/db/cmd/cmd_i
depends on https://github.com/radare/radare2/pull/13352
=> Fix izzz test output

new/db/cmd/cmd_i
Fixed `it` command test.
Related to radare/radare2#13441
=> Fixed `it` command test

new/db/io/cache
`wcr` cache reset test added. Tests that there is no any error printed to stderr
=> Cache reset test added

new/db/cmd/cmd_flags
Test cases for radare/radare2#13555.
(For some reason, my git seems bugged out and labels changes that don't actually exist. I tried hard resetting, deleting master branch and re-checkout, even re-cloning the whole repository but the problem still persists. Anyone knows what's wrong?)
=> Add test cases for base64-armored flag comments

new/db/cmd/cmd_ec
Added test for radare/radare2#13602.
=>  Test whether ec* shows bgcolor too for fgbg color

new/db/cmd/cmd_pf_elf
Added test for radare/radare2#13610.
=> Test pf.elf_header from elf32 pfo

new/db/anal/x86_32, new/db/cmd/cmd_pf, new/db/cmd/cmd_pf_elf, new/db/cmd/types
Added test for radare/radare2#13627.
=> Test whether pf z honors scr.strconv and str.escbslash

new/db/cmd/cmd_pf_elf
Added test for radare/radare2#13649.
=> Test pf.elf_header from elf64 pfo

new/db/cmd/cmd_pf_elf
Added tests for radare/radare2#13657.
=> Test updated -nn format in elf.c

new/db/cmd/cmd_pf_elf
Added test for radare/radare2#13691.
=>  Test pfj ]}, fix for struct nested to 1 level

new/db/cmd/types
Corresponds to PR https://github.com/radare/radare2/pull/13632 and issue https://github.com/radare/radare2/issues/13607
=> Update tsc/tuc/tec tests

unit/minunit.h, unit/test_uleb128.c
r2 PR: https://github.com/radare/radare2/pull/13676
=> Add tests for leb128 functions

new/db/cmd/cmd_pf2
Added test for radare/radare2#13740.
=> Test pfj z when z is not at struct start

new/db/cmd/cmd_pf2, new/db/cmd/cmd_pf_elf
Added test for radare/radare2#13761.
=>  Test whether pfj z honors size

new/db/formats/mach0/mach0, unit/test_buf.c
r2 PR: https://github.com/radare/radare2/pull/13807
=> Add r_buf_get_string unit test

new/db/cmd/cmd_pf_elf
Added test for radare/radare2#13884.
=>  Test pfs handling of {times}

new/db/cmd/cmd_pf2, new/db/cmd/cmd_pf_elf
Added/changed tests based on radare/radare2#13892.
=> Test whether pf? <fmt_name> works properly

new/db/anal/x86_32, new/db/anal/x86_64
I realized I misnamed the branch so I closed my old PR and opened this one.
Related to this PR: radare/radare2#13887
=> Update ao tests

r2r
Faster to type `./r2r`  than `node ...` .
=> Fix r2r (the sh script)

r2r
=> r2r script: R2R env var decides r2r command line

new/db/cmd/print
https://github.com/radare/radare2/pull/14051 related
=> Test pfc nested

new/db/cmd/cmd_ec
Added test for radare/radare2#14076.
=> Test ansicon ecs

new/db/cmd/cmd_ec
Fixed test for radare/radare2#14232.
=> Test whether bright colors are used instead of bold in default palette

new/db/cmd/cmd_ec
Added test for radare/radare2#14257.
=> Test eco bright

new/db/cmd/cmd_ec
Fixed test for radare/radare2#14273.
=> Test eco bright and bold

new/db/cmd/cmd_zignature
depends on https://github.com/radare/radare2/pull/14281
=> Fix zignatures tests for explicit masks

new/db/cmd/cmd_ec
Fixed test due to radare/radare2#14283.
=> Test ecd bright-bold

new/db/cmd/cmd_ahi, new/db/cmd/cmd_pd
Fixed tests due to radare/radare2#14304.
=> Fix cmd_ahi and cmd_pd tests due to eip inverse fix

new/db/esil/arm_32
depends on: https://github.com/radare/radare2/pull/14326
=> Fix LS, LE arm conditions

new/db/asm/arm_64
- regressions ensuring correct assembling of xzr operand
=> Arm64: XZR assembler regression tests

new/db/cmd/cmd_pd
Added test for radare/radare2#14402.
=> Test ds_begin_nl_comment color

new/db/cmd/types
Closes https://github.com/radare/radare2-regressions/issues/1723.
Review, please!
=> Add test for tn, tn-

bins/other/palette.r2, new/db/cmd/cmd_ec
Added test for radare/radare2#14421.
=> Test ec* wrt attributes

new/db/cmd/cmd_pd2
Added test for radare/radare2#14592.
=>  Test demangled comment order

new/db/cmd/cmd_i, new/db/formats/mach0/objc
related to https://github.com/radare/radare2/pull/14629
=> Fix icc and ic for ObjC parent class

new/db/cmd/cmd_pf, new/db/formats/mach0/mach0
related to: https://github.com/radare/radare2/pull/14670
=> Fix tests for Mach-O headers and format defs

new/db/formats/mangling/bin
Added test for radare/radare2#14668.
=>  Test whether flag name is shown for internal demangled xref

new/db/cmd/cmd_i, new/db/formats/mach0/mach0
related to: https://github.com/radare/radare2/pull/14679
=> Fix test for macho sdb formats

new/db/cmd/types
Adding tests for https://github.com/radare/radare2/issues/12267
Please review.
=> Add tests for unions with "to"

new/db/anal/x86_32, new/db/anal/x86_64, new/db/cmd/cmd_json, new/db/cmd/cmd_pdr, new/db/cmd/cmd_print, new/db/cmd/cmd_seek, new/db/cmd/midbb, new/db/formats/mdmp
For https://github.com/radare/radare2/pull/14717
=> Fix tests for #14717

new/db/anal/x86_64, new/db/cmd/cmd_pd2
Added test for radare/radare2#14760.
=> Test newlined-comment-refline fix

new/db/anal/x86_64, new/db/cmd/cmd_pd2, new/db/cmd/noreturn, new/db/formats/elf/helloworld-gcc-elf, new/db/formats/elf/thumb, new/db/formats/mach0/fatio, new/db/formats/pe/tls_noEP
Added test for radare/radare2#14766.
=> Test pi rip-relative addressing when scr.color=0

new/db/anal/x86_64, new/db/cmd/cmd_pd2, new/db/cmd/types
Added test for radare/radare2#14773.
=> Test rip-relative flag fix

new/db/cmd/types, new/package.json
https://github.com/radare/radare2/issues/14764
=>  Fix type test for Windows

new/db/anal/x86_64, new/db/formats/elf/crackme7, new/db/io/baddr
related to https://github.com/radare/radare2/pull/14793
=> tests fix after noreturn propagation improvment

new/db/io/baddr
this should fix the non deterministic test issues related to https://github.com/radare/radare2/pull/14793
=> sort before diff

new/db/anal/x86_64, new/db/cmd/cmd_pd, new/db/cmd/cmd_pd2, new/db/formats/mach0/fatio, new/db/formats/pe/tls_noEP
Added/changed tests for radare/radare2#14802.
=> Test bracketing of indirect addr operand (except LEA)

new/db/cmd/cmd_att, new/db/cmd/cmd_pd2
Added test for radare/radare2#14895.
=> Test LEA section flag bracket fix

new/db/cmd/cmd_pd2
Added test for radare/radare2#14955.
=> Test asm.bb.line glitches fix

new/db/cmd/cmd_pd2
Added test for radare/radare2#14961.
=> Test esil call no-fcn-name comment alignment fix

new/db/cmd/cmd_pd2
Added test for radare/radare2#14972.
=> Test whether asm.bb.lines shows bblines between bb and non-bb

new/db/esil/arm_32
This goes with this PR:
https://github.com/radare/radare2/pull/14983
=> esil: add stmia test

new/db/esil/arm_16
See my other pull request for fix in code.
=> test for issue 14850

new/db/cmd/cmd_zignature
Related to https://github.com/radare/radare2/pull/15000
=> Fix tests for zignatures with types

new/db/anal/x86_64
Reverts radareorg/radare2-regressions#1968
=> Revert "Test nonpropagation of noret to fcn if fcn jmps outside itself"

new/db/anal/x86_64
Added test for radare/radare2#15266.
=> Test jumptable support for main() in bins/elf/analysis/ls-alxchk

unit/test_esil_dfg_filter.c
test for https://github.com/radareorg/radare2/pull/15355
=> add unit test for esil dfg filter

new/db/anal/x86_64
Fixes Travis tests for https://github.com/radareorg/radare2/pull/15381.
=> Fix tests for SDB argtypes

new/db/cmd/cmd_pd2
Added test for radareorg/radare2#15450.
=> Test UTF16-BE decoding

new/db/cmd/cmd_pd2
Added test for radareorg/radare2#15472.
=> Test UTF32-BE decoding

new/db/cmd/cmd_pd
Added test for radareorg/radare2#15492.
=> Test bin.str.enc acceptance of UTF hyphen aliases

new/db/cmd/cmd_pd
Added test for radareorg/radare2#15496.
=> Test bin.str.enc acceptance of uppercase aliases

new/db/cmd/cmd_pd2
Added test for radareorg/radare2#15500.
=> Test whether asm.cmt.off accepts 0 & 1 as aliases for false & true respectively

new/db/asm/or1k
Regression tests for pull request radareorg/radare2#15515
=> Add regression tests for or1k

new/db/cmd/cmd_pd
Test for radareorg/radare2#15535.
=> Test scr.onestream workaround
