radareorg/radare2-regressions

files/multiline_prefix.asm, t.asm/labels/prefix
when labels has common prefix and different lengths, replacement breaks the code. it may be an issue of  how equs are replaced, i guess they should be replaced in order of length (longer first).
=> + broken test for asm labels replacement with common prefix

t.anal/mips/mips
+ unBROKEN the mips tests which now works after fixes in anal_mips_cs
+ little housekeeping, removing lines from EXPECT output because some tests did fail only for differecies in ascii art
=> fixed mips tests

t.anal/mips/mips, t.esil/mips
+ corresponds to the new "negative mem reference"
+ refactored to test the feature using emulation
=> moved "mips ESIL subtraction in mem refs" to esil tests

t/search/bug_3788
tests 2 is no longer broken when using search.in=io.sections
=> adds more tests for bug 3788

t/cmd/ahi
Issue https://github.com/radare/radare2/issues/3766 is fixed and we can remove this *BROKEN* flag.
=> ahi test. remove broken flag

t.anal/others_anal/reflines, t/asm/callflag, t/cmd/ahi, t/cmd_disasm, t/cmd_eval, t/cmd_info
Some assumptions were being made about the underlying architecture that caused these tests to fail on 32-bit ARM.
=> Fixed a bunch of failed test on 32-bit ARM

run_tests_parallel.sh
Before these changes, I was missing the output of the tests and the r2 -v output when using run_tests_parallel.sh
```
=== Report ===
[2]   SUCCESS
[0]   FIXED
[2]   BROKEN
[0]   FATAL
[0]   FAILED
[50%]     BROKENNESS
```
as compared to the output of run_tests.sh
```
./run_tests.sh t/sections/
radare2 0.10.0 10251 @ darwin-little-x86-64 git.0.10.0-97-g69c3ffa
commit: 69c3ffa9e6c9444a4be265ee02459c898f51caf1 build: 2016-02-03
[BR]  1  0000:
[BR]  1  glue:
[OK]  1  simple-elf:
[OK]  2  simple-elf: display mapped flag in sections list
=== Report ===
[2]   SUCCESS
[0]   FIXED
[2]   BROKEN
[0]   FATAL
[0]   FAILED
[50%]     BROKENNESS
```
With these changes the test output is back
```
./run_tests_parallel.sh t/sections/
radare2 0.10.0 10251 @ darwin-little-x86-64 git.0.10.0-97-g69c3ffa
commit: …
```
=> don't drop output of tests when max thread count is never reached and use r2 -v in ouput of parallel test run

tests.sh
`stdout` and `stderr` of Windows binaries have `CRLF` separators. `EXPECT` and `EXPECT_ERR` in test scripts have `LF` separators. `diff` should ignore the `CR`-s.
=> Ignore CR separators when comparing stdout/stderr

t.tools/rahash2/rahash2
removed !! from 2 tests to fix execution on MSYS2
added wrong hash case for -c option
added empty string hashes for SHA256/384/512
added test string hashes for SHA256/384/512 from "Descriptions of SHA-256, SHA-384, and SHA-512" by NIST
ref: #150 and https://github.com/radare/radare2/issues/3274
=> rahash2: added more SHA2 test cases

t.io/baddr
This pull request fixes the baddr test case for https://github.com/radare/radare2/pull/4255
=> Adapt baddr to ordered afl

t.asm/ebc/ebc
Besides, a friend has disassembled this using IDA pro, and has obtained
MOVdd       R7, [R7+0x264]
Then, we can compute 0x264 = 4 * 7 + 584 (so IDA seems to emulate 32 bits EFI)
However, neither 2337 + 3 * 4 nor 2337 + 3 * 8 matches 0x264.
=> Actually follow the specification for movdd index

t.anal/z80/basic
Related to radare/radare2#4500.
It tests that analyser finds 3 subroutines, compares their addresses and sizes.
=> Add test for basic analysis for z80

t.archos/Linux-x86_64/dbg_io, t.archos/Linux-x86_64/dbg_step
When tests with /bin/ls are left to run the output from ls sometimes ends up in stdout and makes the test fail artificially. Kill the inferior to prevent this.
=> Kill the child to avoid flaky results

tests.sh
Now that rarun2 supports "--" to treat the remaining stuff as the command line, we can use it's timeout= feature for making sure tests don't hang forever.
=> Set a 5 second timeout for tests using rarun2

t/cmd_ahi
Test if the immediate string base is implemented properly.
In this test only right argument should be changed to string.
=> Immediate string base for right argument.

tests.sh
Running tests on a local machine which is configured for a timezone other than GMT produces failed tests.
This pr is a proposal for a possible workaround for this issue - please feel free to reject.
A proper solution needs to be implemented in r2.
See radare/radare2/issues/2516 and radare/radare2/issues/2111.
=> workaround for tests with timestamps in different TZ

t.asm/x86/nz/x86_asm
Only x86.olly flavour supports short syntax at the moment. Adding tests cases to fix that
=> add tests case for jz "short" syntax

run_unit.sh
@crowell what do you think? at the moment unit tests are not working on OS X (travis or mine)
=> run_unit: change perm to make it work also on OS X

t.asm/x86/nz/x86_asm
Tests for NZ from radare/radare2#5967 
Couple more with segments
Several with instructions that should not be assembled at all
And  `mov [ecx*8+64], eax` which works ok in reverse direction
=> More tests for nz

t.asm/x86/nz/x86_asm
Some way along the last PR the push/pop ops with segment registers were marked as broken again. This PR marks them back as fixed
=> Unbreak push pop ops with segment regs

t.asm/x86/nz/x86_asm
"mov byte [rbp-0x100], 2" was converted to "mov byte [ebp-0x100], 2"
=> Add test for rbp/ebp indexing confusion

t.anal/others_anal/xref
Covers what's broken by https://github.com/radare/radare2/commit/637e6db3e1dff627236ede7f0f302ad4a952bf5c
Refs https://github.com/radare/radare2/issues/5113 (not actually including tests for that yet since i'm not really sure)
Also requires https://github.com/radare/radare2/pull/6145 to not choke with color codes
=> t.anal/others_anal/xref: axf string ref tests

t.esil/arm-16
This documents a possible bug reported in https://github.com/radare/radare2/issues/6389
=> [t.esil] arm-16: add test for load/store multiple instructions (#6389)

t.esil/arm-16
This documents a possible bug reported in [issue #6388](https://github.com/radare/radare2/issues/6388).
=> [t.esil] arm-16: add test for arithmetic shift instruction (#6388)

t.anal/arm/arm_32
Analysis should mark somehow when branches change between 32-bit arm mode and 16-bit thumb mode. It may not be 'af' but that is what the test uses. These tests fail even with 'aaaa'.
=> Added bx changes to thumb mode tests.

t.anal/avr/search
because `aac` isn't seek-independent
=> Fix avr search - aac from 0

t.asm/riscv/riscv32, t.formats/elf/elf-riscv64
- Update `t.formats/elf/elf-riscv64` test for `noalias=false` instructions (https://github.com/radare/radare2/pull/6897)
- Add RiscV disassembly test: Disassemble a mix of 4-byte as well as 2-byte instructions. Checks https://github.com/radare/radare2/pull/6850 https://github.com/radare/radare2/pull/6897.
=> RiscV testing improvements

t.formats/pe/pe64
Switched from pe32+ to pe64 for consistency with radare2 file naming in libr.
=> pe32+ -> pe64

t/cmd_write
The test for cmd_wci:
-  uses radiff2 instead of cmp.
- removes the temp folder.
- uses src.null=true.
=> Test for cmd_wci uses radiff2 and it is simplified.

t.anal/others_anal/xref
The `qword` in `call qword` already shows that the call is indirect.
=> Fixed xref tests related to radare/radare2#7192

unit/test_diff.c
This runs a small handful of tests of r_diff_buffers_distance. Unfortunately one of the implementations already fails one of the tests; the ifdeffed out test produces different results with or without levenstein mode. As I'm not certain what distance measure is in use for non-levenstein, I'm not certain if that is a test bug or libr bug. 
This should catch the bug where similarity was not set if distance was missing.
=> Initial test for binary diff routine

t/cmd_search
This reverts the extra backslash added in the wrong place by cfa30d06 and adds an extra 0x5c byte at the end of the searched string so that there's a backslash to test escaping for r2 PR 7294
For https://github.com/radare/radare2/pull/7294
=> cmd_search: remove extra backslash, add another one at the end

t.anal/others_anal/aac
Analysis was discarding the branch likely targets and including many 'loc' references and an errant 'sym.imp.__umoddi3'.
Tests pass with radare/radare2#7360
=> Update aac test with MIPS likely branches analyzed

t.anal/others_anal/reflines, t/cmd_pd, t/noreturn, t/pdf
Tests for radare/radare2#7398. Supersedes #827.
=> Tests whether refaddr is shown only once in cmts

t.asm/mips/mips
- set “v2” cpu for coprocessor 3 instructions
- unbroken SD test
to be merged after https://github.com/radare/radare2/pull/7643
=> Fix mips asm tests

t/cmd_search, t/cmd_search_hit
Fixed tests for radare/radare2#7659.
=> Fixed tests where search with json output escapes twice

t.archos/Linux-x86_64/dbg_step_back
Add debug step back test to t.archos.
TODO: dsb has still bug related to recovering syscall results and repeated using of dsb. 
Fix these and add more tests too.
=> Add dsb command test

t/cmd_pd
=> Tests whether there is no | highlight with asm.cmtright=false and call statement

t.anal/arm/arm_16
Fixed to reflect this fact: in THUMB mode all pc-relative loads have an offset if 4 bytes, regardless of the size of the instruction.
This test is now broken because of this: https://github.com/radare/radare2/blame/master/libr/anal/p/anal_arm_cs.c#L1338
Instead i observed that the above commented "theory" calculation of `pcdelta` should be used instead. (assuming that `thumb` flag is passed correctly to anal, ofc.) /cc @alvarofe
=> Fix thumb ldr pc-relative tests

t/cmd_i
=> Tests whether iz correctly prints utf16le strings

t/cmd_i
Tests for radare/radare2#8242.
=> Tests whether izj/izzj includes Unicode blocks correctly

t.anal/arm/signext
According to condret, we can use `om ` as an alternative when the `S ` command for memory mirroring is still disputable.
=> Fix t.anal/arm/signext , the semantics of "S " has changed since siol

t/feat_grep
Without quotes, the following usage message is shown:
```
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
```
=> Add quotes to "count grep" test name

t/metadata
As per https://github.com/radare/radare2/pull/8464#issuecomment-328827104.
=> Tests whether a range.<baddr> key affects the output of C[Chsdmf][*]

t/cmd_i
'ibk' test is just to prevent regression as found by fuzzer
in https://github.com/radare/radare2/issues/8601
=> Add functional test for 'ik' and 'ibk'

t/metadata
Tests for radare/radare2#8630. The string at 0x140016018 is actually utf16le.
=> Tests whether Csa works correctly

Makefile, t.formats/mdmp/mdmp
Moved the tests to the correct location for the core and added to a test for `pf.` (as requested).
=> mdmp: moved mdmp to the core hence moved the tests

t/cmd_types
This is for the https://github.com/radare/radare2/pull/8798
Note, that those changes required, since "int" not interpreted as "int32_t", to be absolutely precise about the size. In the future the size of int may change depending on the target binary/debugee, so this is required for a seamless data types interpretation.
=> Fix TCC tests

t.esil/arm-64, t.esil/x86-32
Tests based on specific cases from @radare.
=> Tests whether no ESIL string is displayed for jmp (x86) and cbz (AArch64)

new/db/asm/x86_64
In anticipation of a PR for https://github.com/radare/radare2/issues/8939.
> Unless we explicitly override the operand size with e.g. a `dword ptr` qualifier, we should emit an instruction with a REX prefix of 0x48 (W bit set) to indicate a 64-bit operand.
In reality, there's room for debate: other assemblers consider the case `mov [rbp+4], 0` to be ambiguous, and _require_ an operand size qualifier. In rasm, we seem to allow this ambiguity. My existing patch (https://github.com/ranweiler/radare2/commit/25295d42fb782f33b6d5f37913a3e2b1bdb6d3ff, which adds the 0x48 prefix) is only hit if `bits == 64` and we've already flagged the operand as 64-bit, in which case I think it is appropriate to expect an unqualified `mov` to memory to assemble as if we included `qword ptr`.
I'm open to other …
=> Fix expected x86 assembler result for a 64-bit immediate mov to mem

t/cmd_pd, t/cmd_pd_bugs
special chars in like /n, /t, etc. are removed in str flags in regression tests
=> Fixing expected strings for pr #8972 radare2

t.esil/arm-64
See https://github.com/radare/radare2/issues/9443
It was only tested ldp doesn't mess things up, but not the actual loads.
=> Fix aarch64 ldp test

new/bin/r2r.js
```
$ ./bin/r2r.js -h
Usage: r2r [options] [file] [name] ([cmds])
-a    add new test
-b    mark failing tests as broken
-c    use -c instead of -i to run r2 (EXPERIMENTAL)
-d    delete test
-e    edit test
-f    fix tests that are not passing
-i    interactive mode
-j    output in JSON
-l    list all tests
-u    unmark broken in fixed tests
-v    be verbose (show broken tests and use more newlines)
```
=> Fix r2r.js -h hang, trim usage message

new/bin/r2r.js
Useful if only a few characters have changed in a long line of characters. Demo:
=> Allow diff by character comparison

t.esil/x86-64
Related to #9647 in radare2 repo.
=> Fix test for imul 1 arg in x86-64

t.formats/pdb/pdb
This fix should make master green again.
Unfortunately it seems that `!` command followed by a pipe `|` does't redirect stderr.
But changing it to `!!` and using `~` works correctly.
=> Fix pdb-downloader not redirecting stderr to grep

t.anal/others_anal/cmd_anal_fcn
Fixes a small test running `agf`
This fixes pr https://github.com/radare/radare2/pull/10187
Removes shortcuts since they are useless when the graph is non interactive.
=> Removed shortcuts in non-interactive graph test

new/db/asm/x86_32
Test case for https://github.com/radare/radare2/issues/11249
assemble instruction: xor byte [eax], 0xff -> 8030FF
=> x86_32 - assemble xor byte [eax], 0xff

new/package.json
You dont support under node 8
```
TypeError: promisify is not a function
at Object.<anonymous> (/Users/jacobrosenthal/Downloads/radare2-regressions/new/index.js:9:21)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:389:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:504:3
```
So be explicit in the package.json with an engines field. And support npm link (and just manual understanding of what file is to be run) by using bin field
=> be more node standard

new/db/cmd/cmd_pd2
Added test for radare/radare2#11612.
=> Test whether bytes are correctly shown for invalid opcodes

README.md
Since it use util.promisify, it need node 8, which exclude
RHEL 7
=> Add a minimum version of nodeJS

new/db/anal/x86_2
Added tests for radare/radare2#12019.
=> Add tests for anal.jmpmid (x86, no loops)

new/db/cmd/cmd_pd2
Modified tests for radare/radare2#12571.
=> Test asm.bbline when there is only backwards ref from addr

new/db/anal/arm
after analysis, the _start symbol should still be there.
=> fix analysis arm test

new/db/tools/rasm2
I changed the implementation a bit to remove the new line after the  }. 
For pr https://github.com/radare/radare2/pull/13025
=> Fixed the test for rasm -Aj

new/db/cmd/cmd_pd2
Modified tests for radare/radare2#13214 and radare/radare2#13193.
=>  Test whether x86 afb+ updates size in fcn rbtree after adding bb

new/db/cmd/cmd_ownshell, new/db/cmd/cmd_project, new/db/tools/rabin2
This fixes fails in Windows systems that don't have a C:\tmp folder
=> Use local .tmp folder for tests

new/db/cmd/cmd_pf_elf
Fixed test due to radare/radare2#13734.
=> Fix test due to usage of r_str_escape_utf8_for_json() for pfj z

new/db/cmd/feat_foreach
Added test for radare/radare2#13935.
=>  Test whether extra stderr blank line is prevented when using @@= with `prz`

new/db/formats/mdmp
Add tests for number of strings in the data sections, this should catch the previous bug.
=> mdmp: add a tests to count strings in data sections

new/db/formats/mangling/bin
Added test for radare/radare2#14678.
=>  Test whether demangled xref comment is broken in graph

new/db/cmd/cmd_pd2, new/db/cmd/types
Added/fixed tests for radare/radare2#14868.
=> Fix tests due to using op->disp instead of op->ptr for disp of x86 CMP (and ACMP)

new/db/cmd/cmd_fnj
As per e1e0658009b04de38cdc6caf024ba3723d5d7c14.
=> Revert cmd_fnj test to original flag

new/db/archos/linux-x64/dbg_bps
I think this test was wrong, as once the process exits (after you do the last `dc`), it is not possible to read data anymore, so it seems right that fffffff is returned, instead of the old value there.
What do you think?
=> There is no data to read when the process being debugged exits

new/db/tools/rasm2
Test for radareorg/radare2#15302.
rasm2 currently does not report some bad thumb instructions as failures, so marking `BROKEN=1` pending fix in PR radareorg/radare2#15303.
=> Add test for radareorg/radare2#15302 invalid arm/thumb branches

new/db/formats/java
Typo fix and ubreaking the test for support old Java format along with the PR for r2 to support those.
=> Typo fix and unbroken the support for old java format

new/db/anal/x86_64
As per https://github.com/radareorg/radare2-regressions/commit/238af86f37eb86a5ff43cbf93a0fae4c5dc4fdc4#diff-f65331988bc948a5d883839f352ba3cfR135-R143. Apparently, `__mh_execute_header` is the [address of the mach header](https://opensource.apple.com/source/cctools/cctools-921/include/mach-o/ldsyms.h.auto.html).
=> Revert "sym is not fcn" test to original flag

new/db/archos/linux-x64/dbg_bps
Reverts radareorg/radare2-regressions#1991
=> Revert "There is no data to read when the process being debugged exits"

r2r, r2r.1
Fixes the
```
find: ‘t*’: No such file or directory
```
error when running tests in a newly-cloned r2r.
=> Remove old t*/ testrunner code
